[package]
name = "ph-sensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
serde = { version = "1.0.197", features = ["derive"] }
ctrlc = "3.4.2"
