name: pH Sensor Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Merge with main
      run: |
        git checkout main
        git merge $GITHUB_REF_NAME
    - name: Build
      working-directory: ph-sensor
      run: cargo build --verbose
    - name: Run tests
      working-directory: ph-sensor
      run: cargo test --verbose
