name: pH Sensor Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
       git config --global user.email "name@example.com"
       git config --global user.name "Name"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Merge with main (manual run)
      run: |
        git checkout main
        git merge origin/${{ GITHUB_REF_NAME }}
      if: github.event_name != 'pull_request'
    - name: Merge with main (pull request)
      run: |
        git checkout main
        git merge $GITHUB_HEAD_REF
      if: github.event_name == 'pull_request'
    - name: Build
      working-directory: ph-sensor
      run: cargo build --verbose
    - name: Run tests
      working-directory: ph-sensor
      run: cargo test --verbose
